name: Android CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout código-fonte
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Permitir execução do Gradle
        run: chmod +x ./gradlew

      - name: Build Debug
        run: ./gradlew assembleDebug

      - name: Rodar testes unitários
        run: ./gradlew testDebugUnitTest

      - name: Build Release Assinado
        run: ./gradlew assembleRelease

      - name: Upload APK Debug
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk
